#version 430
layout(local_size_x=256) in;

layout(binding=2) uniform ParameterUBO {
   float dt;
} ubo;
layout(std430, binding=0) buffer position_block { vec4 positions[]; };
layout(std430, binding=1) buffer velocity_block { vec4 velocities[]; };

void main() {
   int index = int(gl_GlobalInvocationID);
   vec4 position = positions[index];
   vec4 velocity = velocities[index];
   position.xyz += ubo.dt*velocity.xyz;
   positions[index] = position;
}